services:
  etheos-dashboard:
    image: ghcr.io/connor93/etheos-dashboard:latest
    container_name: etheos-dashboard
    restart: unless-stopped
    networks:
      - web
    volumes:
      - etheos-dashboard-backups:/data/backups

networks:
  web:
    external: true

volumes:
  etheos-dashboard-backups:
